name: .NET

on:
  create:
    branches: 
      - release/**
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CONFIGURATION: 'Release'
  SOLUTION: 'src/SyslogDecodeAll.sln'

jobs:
  determine_version:
    name: Determine Version
    runs-on: ubuntu-latest
    outputs:
      SemVer: ${{ steps.gitversion.outputs.SemVer }}
      PreReleaseTag: ${{ steps.gitversion.outputs.PreReleaseTag }}
      MajorMinorPatch: ${{ steps.gitversion.outputs.MajorMinorPatch }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.9
        with:
          versionSpec: '5.x'

      - name: Run GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.9

  build:
    name: Build and Package
    runs-on: windows-latest
    needs: determine_version

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: latest

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Restore dependencies
        run: dotnet restore ${{ env.SOLUTION }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION }} --configuration ${{ env.CONFIGURATION }} --no-restore
      
      - name: Package
        run: dotnet pack ${{ env.SOLUTION }} --configuration ${{ env.CONFIGURATION }} --version-suffix ${{ needs.determine_version.outputs.MajorMinorPatch }} --no-restore

      - uses: actions/upload-artifact@v2
        with:
          name: syslog-decode-artifacts
          path: ${{ github.workspace }}\src\SyslogDecode\bin\${{ env.CONFIGURATION }}

  publish:
    name: Publish NuGet Package
    needs: 
      - determine_version
      - build
    runs-on: windows-latest
    steps:
      - name: Download NuGet Package
        uses: actions/download-artifact@v1
        with:
          name: syslog-decode-artifacts

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: '5.x'
          nuget-api-key: ${{ github.token }}
          nuget-api-key-source: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
          
      - name: List files
        run: dir /s *.*

      - name: Publish to GitHub
        run: dotnet nuget push "syslog-decode-artifacts\*.nupkg" -Source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --api-key ${{ github.token }}
