name: build-deploy

on:
  push:
    branches:
      - main
      - release/*
      - feature/*
  pull_request:
    branches:
      - main
      - release/*
      - feature/*

permissions: write-all

env:
  CONFIGURATION: 'Release'
  SOLUTION: 'src/SyslogDecodeAll.sln'

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: 6.0.x

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
            versionSpec: '5.x'

      - name: Check out Code
        uses: actions/checkout@v2
        with:
            fetch-depth: 0

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
            useConfigFile: true
            configFilePath: ./.github/gitversion.yml

      - name: Restore Dependencies
        run: dotnet restore ${{ env.SOLUTION }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION }} --configuration ${{ env.CONFIGURATION }} --no-restore /p:Version=${{ steps.gitversion.outputs.AssemblySemVer }} /p:AssemblyVersion=${{ steps.gitversion.outputs.AssemblySemVer }} /p:InformationalVersion=${{ steps.gitversion.outputs.InformationalVersion }}

      - name: Package
        run: dotnet pack SyslogDecode\SyslogDecode.csproj --configuration ${{ env.CONFIGURATION }} -o:package /p:PackageVersion=${{ steps.gitversion.outputs.AssemblySemVer }}

      #- name: Add NuGet sources
      #  run: dotnet nuget add source --username USERNAME --password ${{ github.token }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

      #- name: Publish to GitHub
      #  run: dotnet nuget push ./package/*.nupkg --source github  --skip-duplicate
      - name: Install GPR
        run: dotnet tool install -g gpr --no-cache -v q

      - name: GPR Push
        run: gpr push --api-key ${{ secrets.GHA_PAT }} ./package/*.nupkg